-- Run this SQL in your Supabase SQL Editor to set up the necessary tables

-- 1. Create the Leaderboard table
CREATE TABLE IF NOT EXISTS leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  ts TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow anyone to read, allow anyone to upsert)
CREATE POLICY "Allow public read" ON leaderboard FOR SELECT USING (true);
CREATE POLICY "Allow public upsert" ON leaderboard FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update" ON leaderboard FOR UPDATE USING (true);

-- 2. Create the Suggestions table
CREATE TABLE IF NOT EXISTS suggestions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  player_name TEXT,
  ts TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE suggestions ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow anyone to insert, hide from public read for privacy)
CREATE POLICY "Allow public insert" ON suggestions FOR INSERT WITH CHECK (true);
CREATE POLICY "Service role read only" ON suggestions FOR SELECT USING (false);
